name: CI

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Node
          uses: actions/setup-node@v2
          with:
            node-version: 15

        - uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - run: npm ci --prefer-offline

        - run: npm run build

        - name: Check if essential files are generated"
          run: |
            test -f dist/manifest.json
            test -f dist/app.*.css
            test -f dist/app.*.css.gz
            test -f dist/app.*.css.map
            test -f dist/app.*.css.map.gz
            test -f dist/app.*.js
            test -f dist/app.*.js.gz
            test -f dist/app.*.js.map
            test -f dist/app.*.js.map.gz
            test -f dist/vendor.*.js
            test -f dist/vendor.*.js.gz
            test -f dist/vendor.*.js.map
            test -f dist/vendor.*.js.map.gz
